name: 'Application'
"on":
  push:
    branches:
      - master
      - next
      - main
      - beta
      - "*.x"

jobs:
  npm-build:
    runs-on: ubuntu-latest
    env:
       working-directory: ./services/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set short sha
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: NPM install step
        run: |
          npm install
        working-directory: ${{env.working-directory}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: |
            ${{env.working-directory}}
            '!${{env.working-directory}}/gitignore'
          retention-days: 5

    outputs:
      sha_short: ${{ steps.sha_short.outputs.sha_short }}