name: 'Application'
"on":
  push:
    branches:
      - master
      - next
      - main
      - beta
      - "*.x"

jobs:
  npm-build:
    runs-on: ubuntu-latest
    env:
       working-directory: ./services/frontend
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set short sha
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: NPM install step
        run: |
          npm install
        working-directory: ${{env.working-directory}}

      - run: npx semantic-release@21.0.2

      - name: Tar files
        run: |
          tar -czvf application.tar.gz ./services/frontend/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: application.tar.gz
          retention-days: 5

    outputs:
      sha_short: ${{ steps.sha_short.outputs.sha_short }}